web:
    build: .
    dockerfile: web.dockerfile
    ports:
        - 8080:80
    volumes:
        - ./www:/www
        - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
        - php
php:
    build: .
    dockerfile: php.dockerfile
    volumes:
        - ./www:/www